#!/usr/bin/env bash
#
# ^ Normally I hate writing a bash script and not a vanilla /bin/sh but 
# since this is for the RPi I think it's a reasonable assumption that bash
# is available.

killprocs ()
{
	logger -i rpaw "Killing existing RPAW processes"
	killall -q omxplayer omxplayer.bin rpaw-wrapper
}

if [ "$1" == "stop" ]
then
	killprocs
	exit 0
fi

if [ ! -r /dev/vchiq ]
then
	echo "Unable to read /dev/vchiq, possible permissions issue."
	exit 1
fi

for f in /usr/local/etc/rpaw.conf /etc/rpaw.conf ./rpaw.conf
do
	if [ -f $f ]
	then
	    source $f
	fi
done

killprocs

sleep 2

logger -i rpaw "Launching Camera Feeds"

# This first rpaw is an M3027 camera and we specify camera=2 to pull the "Panorama" video stream instead of the raw stream
nohup /usr/sbin/rpaw-wrapper --win '0 0 960 540' --live "rtsp://$USERNAME:$PASSWORD@axis-01.example.org/axis-media/media.amp?videocodec=h264&camera=2" &

# The rest are normal AXIS streams 
nohup /usr/sbin/rpaw-wrapper --win '961 0 1920 540' --live "rtsp://$USERNAME:$PASSWORD@axis-02.example.org/axis-media/media.amp?resolution=800x600&clock=0&date=0" &
nohup /usr/sbin/rpaw-wrapper --win '0 541 960 1080' --live "rtsp://$USERNAME:$PASSWORD@axis-03.example.org/axis-media/media.amp?resolution=800x600&clock=0&date=0" &
nohup /usr/sbin/rpaw-wrapper --win '961 541 1920 1080' --live "rtsp://$USERNAME:$PASSWORD@axis-04.example.org/axis-media/media.amp?resolution=800x600&clock=0&date=0" &
